### ISSUE TITLE
License

### ISSUE THREAD

**Issue by andycraig** [fastforwardlabs/cml_churn_demo_mlops#5]
Hi, thank you for releasing this demo. I'm finding it a very useful reference. Would you consider adding a license for it?

**Comment by cjwallace** [comment]
Hi Andy. Glad you're finding it useful! There's an "official" release of this same repo at [cloudera/CML_AMP_Churn_Prediction](https://github.com/) as an [Applied ML Prototype](https://cloudera.github.io/Applied-ML-Prototypes/#/) ("AMP"), all of which are licensed under Apache 2.0, with source available on the Cloudera GitHub.

**Comment by andycraig** [comment]
Hi @cjwallace, thank you for your reply. The file I'm specifically interested in is [8_build_project.py](https://github.com/fastforwardlabs/cml_churn_demo_mlops/blob/master/8_build_project.py) which doesn't seem to have an equivalent at [cloudera/CML_AMP_Churn_Prediction](https://github.com/cloudera/CML_AMP_Churn_Prediction). Do you think this file might be migrated over to the official release at some point?

**Comment by cjwallace** [comment]
Gotcha. The "equivalent" file in the other repo is [.project-metadata.yaml](https://github.com/cloudera/CML_AMP_Churn_Prediction/blob/master/.project-metadata.yaml).

The file you mention uses the unofficial and unsupported [cmlbootstrap](https://github.com/fastforwardlabs/cmlbootstrap) library to interact with the private CML API, so won't be ported. However, most of the same things can be achieved by the (official and supported) [declarative project specification](https://docs.cloudera.com/machine-learning/cloud/applied-ml-prototypes/topics/ml-amp-project-spec.html). An example spec for that project is in that `.project-metadata.yaml` file, covering creating and running jobs, models and applications. On a quick look, it is missing an example of configuring an experiment, but such an example is given in the linked docs.

Hopefully you find declarative projects a lot nicer to use, and we're grateful for feedback! For things that need programmatic, rather than declarative, control, we're working on APIv2 (which comes with a Python library, and as such doesn't require anything unofficial). It's currently Beta, docs are [here](https://docs.cloudera.com/machine-learning/cloud/api/topics/ml-api-v2.html).

Hope this helps!

**Comment by andycraig** [comment]
Thank you for the additional information and links!

In this case the particular functionality I'm after is programmatically creating Jobs. I'll keep an eye on APIv2 as it progresses.

Thanks again, and I'll close this issue now.
